- hosts: '{{ target | default("all") }}'

  roles:
  - openvpn

  vars:
    openvpn_use_pam: no
    openvpn_client_options:
    - redirect-gateway autolocal
    openvpn_server_hostname: "{{ ansible_host }}"
    clients:
    - client
    openvpn_dualstack: false
    # Disable 'register-dns' as it only works on Windows
    openvpn_client_register_dns: false
    # Don't let the role control iptables as this causes issues
    # in cloud environments
    manage_firewall_rules: false

    keys_out: ~/VPN/

  post_tasks:
  - name: Make sure OpenVPN is running
    systemd:
      name: "openvpn@openvpn_{{openvpn_proto}}_{{openvpn_port}}"
      state: started
      enabled: yes
    tags:
    - post-tasks

  - name: Fetch user keys and certificates
    synchronize:
      src: "{{ openvpn_key_dir }}/{{ item }}"
      dest: "{{ keys_out }}"
      mode: pull
    with_items:
    - ca.crt
    - client.crt
    - client.key
    - "../client-{{inventory_hostname}}.ovpn"
    tags:
    - post-tasks
