- hosts: '{{ target | default("all") }}'

  roles:
  - openvpn

  vars:
    openvpn_use_pam: no
    openvpn_client_options:
    - redirect-gateway autolocal
    openvpn_host: "{{ ansible_host }}"

    keys_out: ~/vScaler/VPN/

  post_tasks:
  - name: Make sure OpenVPN is running
    systemd:
      name: openvpn@server
      state: started
      enabled: yes
    tags:
    - post-tasks

  - name: Fetch user keys and certificates
    synchronize:
      src: "{{ openvpn_keydir }}/{{ item }}"
      dest: "{{ keys_out }}"
      mode: pull
    with_items:
    - ca.crt
    - client.crt
    - client.key
    - client.ovpn
    tags:
    - post-tasks
